### PR TITLE
bumping the module version to 1.0.1

### PR DESCRIPTION
**Pull request by evshvarov**
To make it be published in registry

### CODE REVIEW

**Comment by diashenrique** [comment]
Sorry @evshvarov 
But I was trying to revert the version of the app in the OpenExchange to 1.0.0, because I just upload the image logo. And because of my lack of knowledge, I just delete the app and published it again. After all those steps, seeing your pull request just make me feel bad.

**Comment by evshvarov** [comment]
No worries! ZPM Registry is another app where your app is still published with version 1.0.0. So it will not be updated until we either increase the version number or we can delete it on ZPM too.

**Comment by diashenrique** [comment]
OMG!
I don't know. What would be the best practice in this scenario?

**Comment by evshvarov** [comment]
No worries again)
We both want your app to be updated on ZPM.
The simplest way is to CHANGE the version of zpm module to make it different from which already published.
If you look [here ](https://pm.community.intersystems.com/packages/-/all) we see  {"name":"iris-message-viewer","versions":["1.0.0"]} published.
E.g. make it 1.0.1, I approve the request and we have the new module published on the registry.
Very simple.

**Comment by evshvarov** [comment]
Done, thank you!
Now you know everything how zpm-module auto-publishing works )

**Pull request merged**
